package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.stang.game.entity.detail.EntityRightUserDetail;
import com.stang.game.service.impl.RightUserServiceImpl;
import java.util.HashMap;
import java.util.List;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>左边树形菜单</title>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"common/css/page.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"common/js/jquery.min_alixixi_com.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"ul.side_nav li\").hover(function() {\r\n");
      out.write("\t\t$(this).find(\"div\").stop()\r\n");
      out.write("\t\t.animate({left: \"210\", opacity:1}, \"fast\")\r\n");
      out.write("\t\t.css(\"display\",\"block\")\r\n");
      out.write("\r\n");
      out.write("\t}, function() {\r\n");
      out.write("\t\t$(this).find(\"div\").stop()\r\n");
      out.write("\t\t.animate({left: \"0\", opacity: 0}, \"fast\")\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function show_menu(_id)\r\n");
      out.write("{\r\n");
      out.write("\tvar db=document.getElementById(_id);\r\n");
      out.write("\tif(db.style.display==\"none\"){\r\n");
      out.write("\t\tdb.style.display=\"block\";\r\n");
      out.write("\t}else\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdb.style.display=\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fram(_url)\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById('i_f').src=_url;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"width:100%;height:1000px\">\r\n");
      out.write("<table style=\"widht:100%;height:100%\">\r\n");
      out.write("<tr><td style=\"height:100%\">\r\n");

int WEB_RIGHT=1;

HashMap<String, Object> param = new HashMap<String, Object>();
param.put("uid", (Integer)session.getAttribute("uid"));
List<EntityRightUserDetail> eruds = new RightUserServiceImpl().findRightUserByMap(param);
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div id=\"left\" style=\"margin-top: 0px;height:100%;float: left;width:200px\">\r\n");
      out.write("\t<ul class=\"side_nav\">\r\n");
      out.write("\t\t");

if(eruds.size()>=1){
WEB_RIGHT = 2;
 if(eruds.get(0).getRight_value()==2){
	
	 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('news')\">GM工具</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"news\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('message.action')\" class=\"sub_menu\">系统消息</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('messagetwo.action')\" class=\"sub_menu\">更新服务端缓存</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('roletwo.action')\" class=\"sub_menu\">更新用户模型表</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('list.action')\" class=\"sub_menu\">会员充值查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('listcoin.action')\" class=\"sub_menu\">coin表查询</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('geigiftjsp.action')\" class=\"sub_menu\">礼包发送</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('serverlistjsp.action')\" class=\"sub_menu\">服务器状态</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("   </ul> \r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('fuwustatus.action')\" class=\"sub_menu\">开服停服</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('huodongmanager.action')\" class=\"sub_menu\">活动管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("         ");
}
         if(eruds.get(0).getRight_value()==1){

 	
      out.write("\r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('admin_info')\">系统管理</a>\r\n");
      out.write("\r\n");
      out.write("    </li> \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"admin_info\" style=\"display:none\">\r\n");
      out.write("   &nbsp&nbsp&nbsp\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('right.action')\" class=\"sub_menu\">管理员权限管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('logrecord.action')\" class=\"sub_menu\">日志记录</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("       ");

         if(eruds.get(0).getRight_value()==3){

 	
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write(" \t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('news')\">GM工具</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"news\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('message.action')\" class=\"sub_menu\">系统消息</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('messagetwo.action')\" class=\"sub_menu\">更新服务端缓存</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('roletwo.action')\" class=\"sub_menu\">更新用户模型表</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('list.action')\" class=\"sub_menu\">会员充值查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('listcoin.action')\" class=\"sub_menu\">coin表查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('geigiftjsp.action')\" class=\"sub_menu\">礼包发送</a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('serverlistjsp.action')\" class=\"sub_menu\">服务器状态</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('fuwustatus.action')\" class=\"sub_menu\">开服停服</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('huodongmanager.action')\" class=\"sub_menu\">活动管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write(" \t\r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('admin_info')\">系统管理</a>\r\n");
      out.write("\r\n");
      out.write("    </li> \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"admin_info\" style=\"display:none\">\r\n");
      out.write("   &nbsp&nbsp&nbsp\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('right.action')\" class=\"sub_menu\">管理员权限管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('logrecord.action')\" class=\"sub_menu\">日志记录</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("             ");

         if(eruds.get(0).getRight_value()==5){

 	
      out.write("\r\n");
      out.write(" \t \t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('gengxin')\">更新模型表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"gengxin\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('itemlist.action')\" class=\"sub_menu\">gameItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('maplist.action')\" class=\"sub_menu\">gameMap列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('tasklist.action')\" class=\"sub_menu\">gameTask列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equiplist.action')\" class=\"sub_menu\">gameEquip列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('skilllist.action')\" class=\"sub_menu\">gameSkill列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('chlevellist.action')\" class=\"sub_menu\">gameChlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('foelist.action')\" class=\"sub_menu\">gameFoe列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equippropertylist.action')\" class=\"sub_menu\">gameEquipproperty列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bufflist.action')\" class=\"sub_menu\">gameBuffer列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('platlist.action')\" class=\"sub_menu\">gamePlat列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('levellist.action')\" class=\"sub_menu\">gameLevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('mlevellist.action')\" class=\"sub_menu\">gameMlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('militarylist.action')\" class=\"sub_menu\">gameMilitary列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('gamblinglist.action')\" class=\"sub_menu\">gameBlingItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write(" \t\r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('admin_info')\">系统管理</a>\r\n");
      out.write("\r\n");
      out.write("    </li> \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"admin_info\" style=\"display:none\">\r\n");
      out.write("   &nbsp&nbsp&nbsp\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('right.action')\" class=\"sub_menu\">管理员权限管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('logrecord.action')\" class=\"sub_menu\">日志记录</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
if(eruds.get(0).getRight_value()==4){ 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("       \t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('gengxin')\">更新模型表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"gengxin\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('itemlist.action')\" class=\"sub_menu\">gameItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('maplist.action')\" class=\"sub_menu\">gameMap列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('tasklist.action')\" class=\"sub_menu\">gameTask列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equiplist.action')\" class=\"sub_menu\">gameEquip列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('skilllist.action')\" class=\"sub_menu\">gameSkill列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('chlevellist.action')\" class=\"sub_menu\">gameChlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('foelist.action')\" class=\"sub_menu\">gameFoe列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equippropertylist.action')\" class=\"sub_menu\">gameEquipproperty列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bufflist.action')\" class=\"sub_menu\">gameBuffer列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('platlist.action')\" class=\"sub_menu\">gamePlat列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('levellist.action')\" class=\"sub_menu\">gameLevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('mlevellist.action')\" class=\"sub_menu\">gameMlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('militarylist.action')\" class=\"sub_menu\">gameMilitary列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('gamblinglist.action')\" class=\"sub_menu\">gameBlingItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

    if(eruds.get(0).getRight_value()==6){
	
	 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('news')\">GM工具</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"news\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('message.action')\" class=\"sub_menu\">系统消息</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('messagetwo.action')\" class=\"sub_menu\">更新服务端缓存</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('roletwo.action')\" class=\"sub_menu\">更新用户模型表</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('list.action')\" class=\"sub_menu\">会员充值查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('listcoin.action')\" class=\"sub_menu\">coin表查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     \r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('geigiftjsp.action')\" class=\"sub_menu\">礼包发送</a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('serverlistjsp.action')\" class=\"sub_menu\">服务器状态</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("     \t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('gengxin')\">更新模型表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"gengxin\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('itemlist.action')\" class=\"sub_menu\">gameItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('maplist.action')\" class=\"sub_menu\">gameMap列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('tasklist.action')\" class=\"sub_menu\">gameTask列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equiplist.action')\" class=\"sub_menu\">gameEquip列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('skilllist.action')\" class=\"sub_menu\">gameSkill列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('chlevellist.action')\" class=\"sub_menu\">gameChlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('foelist.action')\" class=\"sub_menu\">gameFoe列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equippropertylist.action')\" class=\"sub_menu\">gameEquipproperty列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bufflist.action')\" class=\"sub_menu\">gameBuffer列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('platlist.action')\" class=\"sub_menu\">gamePlat列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('levellist.action')\" class=\"sub_menu\">gameLevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('mlevellist.action')\" class=\"sub_menu\">gameMlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('militarylist.action')\" class=\"sub_menu\">gameMilitary列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('gamblinglist.action')\" class=\"sub_menu\">gameBlingItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('fuwustatus.action')\" class=\"sub_menu\">开服停服</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('huodongmanager.action')\" class=\"sub_menu\">活动管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("         \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

    if(eruds.get(0).getRight_value()==7){
	
	 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('news')\">GM工具</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"news\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('message.action')\" class=\"sub_menu\">系统消息</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('messagetwo.action')\" class=\"sub_menu\">更新服务端缓存</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('roletwo.action')\" class=\"sub_menu\">更新用户模型表</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('list.action')\" class=\"sub_menu\">会员充值查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('listcoin.action')\" class=\"sub_menu\">coin表查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('geigiftjsp.action')\" class=\"sub_menu\">礼包发送</a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("     <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('serverlistjsp.action')\" class=\"sub_menu\">服务器状态</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('activitylist.action')\" class=\"sub_menu\">更新活动</a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("     \t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('gengxin')\">更新模型表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"gengxin\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('itemlist.action')\" class=\"sub_menu\">gameItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('maplist.action')\" class=\"sub_menu\">gameMap列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('tasklist.action')\" class=\"sub_menu\">gameTask列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equiplist.action')\" class=\"sub_menu\">gameEquip列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("  <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('skilllist.action')\" class=\"sub_menu\">gameSkill列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('chlevellist.action')\" class=\"sub_menu\">gameChlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('foelist.action')\" class=\"sub_menu\">gameFoe列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('equippropertylist.action')\" class=\"sub_menu\">gameEquipproperty列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bufflist.action')\" class=\"sub_menu\">gameBuffer列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('platlist.action')\" class=\"sub_menu\">gamePlat列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('levellist.action')\" class=\"sub_menu\">gameLevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('mlevellist.action')\" class=\"sub_menu\">gameMlevel列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('militarylist.action')\" class=\"sub_menu\">gameMilitary列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("       <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bbufflist.action')\" class=\"sub_menu\">gameBbuff列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bmaplist.action')\" class=\"sub_menu\">gameBmap列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('bskilllist.action')\" class=\"sub_menu\">gameBskill列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('missionlist.action')\" class=\"sub_menu\">gameMission列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('binglist.action')\" class=\"sub_menu\">gameBing列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('gamblinglist.action')\" class=\"sub_menu\">gameBlingItem列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('fuwustatus.action')\" class=\"sub_menu\">开服停服</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('huodongmanager.action')\" class=\"sub_menu\">活动管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    <li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('shop.action')\" class=\"sub_menu\">商城打折管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("         \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('admin_info')\">系统管理</a>\r\n");
      out.write("\r\n");
      out.write("    </li> \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"admin_info\" style=\"display:none\">\r\n");
      out.write("   &nbsp&nbsp&nbsp\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('right.action')\" class=\"sub_menu\">管理员权限管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("     \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('logrecord.action')\" class=\"sub_menu\">日志记录</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     ");
}
     else if((Integer)session.getAttribute("uid")==3779){
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('news')\">GM工具</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"news\" style=\"display: none\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('message.action')\" class=\"sub_menu\">系统消息</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('messagetwo.action')\" class=\"sub_menu\">更新服务端缓存</a>\r\n");
      out.write("    \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('list.action')\" class=\"sub_menu\">会员充值查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <br/>\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('listcoin.action')\" class=\"sub_menu\">coin表查询</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <br/>\r\n");
      out.write("    <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('geigiftjsp.action')\" class=\"sub_menu\">礼包发送</a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("     \r\n");
      out.write("  <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('serverlistjsp.action')\" class=\"sub_menu\">服务器状态</a>\r\n");
      out.write("    </li>    \r\n");
      out.write("    <br/>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('itemlist.action')\" class=\"sub_menu\">道具列表</a>\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    </ul> \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("     \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('fuwustatus.action')\" class=\"sub_menu\">开服停服</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("      <br/>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('huodongmanager.action')\" class=\"sub_menu\">活动管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("         \r\n");
      out.write("     <div>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <br/>\r\n");
      out.write("     <li>\r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"show_menu('admin_info')\">系统管理</a>\r\n");
      out.write("\r\n");
      out.write("    </li> \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"admin_info\" style=\"display:none\">\r\n");
      out.write("   &nbsp&nbsp&nbsp\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('right.action')\" class=\"sub_menu\">管理员权限管理</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    \t<li> \r\n");
      out.write("    <a href=\"javascript:void(0)\" onclick=\"fram('logrecord.action')\" class=\"sub_menu\">日志记录</a>\r\n");
      out.write("  \r\n");
      out.write("    </li>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
 
     }
     
     
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</div> </td> <td style=\"height:100%\">\r\n");
      out.write("<div style=\"float:left;width:80%;background-color:#CCC;height:100%;width:100%\" >\r\n");
      out.write("<iframe src=\"\" style=\"width:1024px;height:100%;margin-top: 0px\" scrolling=\"yes\" id=\"i_f\" />\r\n");
      out.write("</div>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
