package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.stang.game.service.impl.*;
import com.stang.game.entity.detail.*;
import java.util.*;

public final class sendGift_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"giftListDiv\" style=\"z-index: 1; display: none; position: absolute; BORDER-RIGHT: 3px outset; BORDER-TOP: 3px outset; BACKGROUND: #ffffff; BORDER-LEFT: 3px outset; BORDER-BOTTOM: 3px outset;\" align=left>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"functionCloseGiftList()\">关&nbsp;闭</a>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t");

					int i = 0;
					int j = 0;
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr ");
      out.print(j % 4 == 0 ? "style='background-color:#dddddd'" : "style='background-color:#eeeeee'");
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						HashMap<String, Object> param = new HashMap<String, Object>();
						List<GameItemDetail> equipList = new GameItemServiceImpl().getGameItem();
						for (GameItemDetail equip : equipList) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" onCLick=\"functionGetGift('");
      out.print(equip.getItemname());
      out.write("','2-1-");
      out.print(equip.getId());
      out.write("')\" />");
      out.print(equip.getItemname());
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t");

					if (++i % 6 == 0) {
					j++;
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr ");
      out.print(j % 4 == 0 ? "style='background-color:#dddddd'" : "style='background-color:#eeeeee'");
      out.write(">\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=6>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=6>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"functionCloseGiftList()\">关&nbsp;闭</a>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form action=\"sendGift.action\" method=\"post\" onSubmit=\"return getSelect()\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<font color=red size=10><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ tip }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</b></font>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<h1>发送道具列表：</h1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;请选择发送道具：\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"isGift\" type=\"checkbox\" onclick=\"return functionIsGift()\" !checked/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"giftDiv\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t道具列表：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"gifts\" name=\"gifts\" multiple=\"multiple\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 150px; height: 250px; overflow-y: hidden;\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"&lt;&lt;-添加\"\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick='document.getElementById(\"giftListDiv\").style.display=\"block\";' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"-&gt;&gt;移除\" onclick=\"giftsDele()\" />\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<table width=\"395\" height=\"240\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t请输入openid：\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"width: 150px\">\r\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"position: relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"uname\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 18px; text-align: center; color: #AB998F; width: 150px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"unamesAdd()\" value=\"添加-&gt;&gt;\" />\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"unamesDele()\" value=\"移除&lt;&lt;-\" />\t\r\n");
      out.write("\t\t\t\t\t\t<p />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"confirms()\" value=\"全选-&gt;&gt;\" />\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"unames\" name=\"unames\" multiple=\"multiple\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 150px; height: 200px; overflow-y: hidden;\">\r\n");
      out.write("                         12\r\n");
      out.write("                         21\r\n");
      out.write("                         <br/>\r\n");
      out.write("                         33\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t请输入serverid：\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"width: 150px\">\r\n");
      out.write("\t\t\t\t\t<td style=\"vertical-align: top\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"position: relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"serverid\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 18px; text-align: center; color: #AB998F; width: 150px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"serveridsAdd()\" value=\"添加-&gt;&gt;\" />\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"serveridsDele()\" value=\"移除&lt;&lt;-\" />\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"serverids\" name=\"serverids\" multiple=\"multiple\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 150px; height: 200px; overflow-y: hidden;\">\r\n");
      out.write("                         12\r\n");
      out.write("                         21\r\n");
      out.write("                         <br/>\r\n");
      out.write("                         33\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"提交\" style=\"width:80px\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"0\" name=\"isGift\" id=\"isGiftHidden\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tvar int_keycode;\r\n");
      out.write("\t\t \r\n");
      out.write("         document.onkeyclick = function( event_e ){  \r\n");
      out.write("             if( window.event )  \r\n");
      out.write("                event_e = window.event;  \r\n");
      out.write("           \tint_keycode = event_e.charCode||event_e.keyCode;  \r\n");
      out.write("         }  \r\n");
      out.write("\r\n");
      out.write("\t\tfunction queryByName(url,name)\r\n");
      out.write("\t\t{\r\n");
      out.write("    \t\tif(int_keycode==13 || int_keycode==38 || int_keycode==40) return;\r\n");
      out.write("    \t\tgetQuery(url,name,backname);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction backname(msg)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar option=\"\";\r\n");
      out.write("    \t\tif(msg.length>0)\r\n");
      out.write("    \t\t{\r\n");
      out.write("       \t\t\toption+=\"<option value='\"+msg[0]+\"' selected>\"+msg[0]+\"</option>\";\r\n");
      out.write("        \t\tfor(var i=1;i<msg.length;i++)\r\n");
      out.write("        \t\t{\r\n");
      out.write("            \t\toption+=\"<option value='\"+msg[i]+\"'>\"+msg[i]+\"</option>\";\r\n");
      out.write("        \t\t}\r\n");
      out.write("\t\t\t\tvar str='<SELECT multiple size=\"11\" id=\"sname\" NAME=\"sname\" onkeyup=\"if(event.keyCode==13){document.getElementById(\\'search\\').style.display=\\'none\\';document.getElementById(\\'uname\\').value=this.value;document.getElementById(\\'uname\\').focus();}\" style=\"width:150px\" onclick=\"document.getElementById(\\'search\\').style.display=\\'none\\';document.getElementById(\\'uname\\').value=this.value\">'+\r\n");
      out.write("\t\t\t\t\toption+\r\n");
      out.write("\t\t\t\t\t'</SELECT>';\r\n");
      out.write("        \tdocument.getElementById(\"search\").innerHTML=str;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"search\").style.display=\"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction panduan(e)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(document.getElementById(\"search\").style.display==\"block\"&&(e.keyCode==38 || e.keyCode==40))\r\n");
      out.write(" \t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"sname\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(e.keyCode==13)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tsearch();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"search\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction unamesAdd(){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("  \t\t\ty.text=document.getElementById(\"uname\").value;\r\n");
      out.write("  \t\t\tvar x=document.getElementById(\"unames\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"uname\").value=\"\";\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction serveridsAdd(){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("  \t\t\ty.text=document.getElementById(\"serverid\").value;\r\n");
      out.write("  \t\t\tvar x=document.getElementById(\"serverids\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"serverid\").value=\"\";\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\tfunction unamesDele(){\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"unames\");\r\n");
      out.write("\t\t\tx.remove(x.selectedIndex);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction serveridsDele(){\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"serverids\");\r\n");
      out.write("\t\t\tx.remove(x.selectedIndex);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction giftsDele(){\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"gifts\");\r\n");
      out.write("\t\t\tx.remove(x.selectedIndex);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionIsGift(){\r\n");
      out.write("\t\t\tif(document.getElementById(\"isGift\").checked){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"giftDiv\").style.display=\"block\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"giftListDiv\").style.display=\"block\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"isGiftHidden\").value=\"1\";\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"giftDiv\").style.display=\"none\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"giftListDiv\").style.display=\"none\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"isGiftHidden\").value=\"0\";\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionCloseGiftList(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"giftListDiv\").style.display=\"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionGetGift(name,value){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("\t\t\ty.text=name;\r\n");
      out.write("\t\t\ty.value=value+\"-\"+y.text;\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"gifts\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction confirms(){\r\n");
      out.write("\t\t//if(confirm(\"是否全选所有用户\")==true){\r\n");
      out.write("\t\t\t//选择是\r\n");
      out.write("\t\tvar y=document.createElement('option');\r\n");
      out.write("  \t\t\ty.text=\"所有用户\";\r\n");
      out.write("  \t\t\tvar x=document.getElementById(\"unames\");\r\n");
      out.write("  \t\t\tx.length=0;\r\n");
      out.write("  //\t\t\tvar sel = document.forms[\"myForm\"].elements[\"sel\"];\r\n");
      out.write("//sel.length = 0; //为0表全清空，为1表留下一项……\r\n");
      out.write("  \t\t\t//x.remove();\r\n");
      out.write("  \t\t\tx.add(y,null);\r\n");
      out.write("\t\t//}else{\r\n");
      out.write("\t\t//\treturn ;\r\n");
      out.write("\t\t//}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionGetGiftItem(name,id,numS){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("\t\t\tvar num = parseInt(numS);\r\n");
      out.write("\t\t\tif(isNaN(num)||num<1){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ty.text=name+\" X\"+num;\r\n");
      out.write("\t\t\ty.value=\"3-\"+num+\"-\"+id+\"-\"+y.text;\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"gifts\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionGetGiftMoney(numS){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("\t\t\tvar num = parseInt(numS);\r\n");
      out.write("\t\t\tif(isNaN(num)||num<1){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ty.text=\"点券\"+\" X\"+num;\r\n");
      out.write("\t\t\ty.value=\"5-\"+num+\"-0-\"+y.text;\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"gifts\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction functionGetGiftGold(numS){\r\n");
      out.write("\t\t\tvar y=document.createElement('option');\r\n");
      out.write("\t\t\tvar num = parseInt(numS);\r\n");
      out.write("\t\t\tif(isNaN(num)||num<1){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ty.text=\"金币\"+\" X\"+num;\r\n");
      out.write("\t\t\ty.value=\"0-\"+num+\"-0-\"+y.text;\r\n");
      out.write("\t\t\tvar x=document.getElementById(\"gifts\");\r\n");
      out.write("  \t\t\ttry\r\n");
      out.write("    \t\t{\r\n");
      out.write("\t\t\t\tx.add(y,null); // standards compliant\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch(ex)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tx.add(y); // IE only\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("//获取用户角色名\r\n");
      out.write("function getQuery(url,name,callBack)\r\n");
      out.write("{\r\n");
      out.write("\tvar xmlHttp;\r\n");
      out.write("\tvar r = function ()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif (xmlHttp.readyState == 4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (xmlHttp.status == 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("    //alert(isIE);\r\n");
      out.write("\t\t\t\tvar xmlstr;\r\n");
      out.write("\t\t\t\t//var xmldoc;\r\n");
      out.write("\t\t\t\t//var isIE = !!(window.attachEvent && !window.opera);\r\n");
      out.write("\t\t\t\t//if (isIE) {\r\n");
      out.write("\t\t\t\t//\txmldoc = xmlHttp.responseXML;\r\n");
      out.write("\t\t\t\t//} else {\r\n");
      out.write("\t\t\t\t\txmlstr = xmlHttp.responseText;\r\n");
      out.write("\t\t\t\t//\talert(xmlstr);\r\n");
      out.write("\t\t\t\t//\tvar parser = new DOMParser();\r\n");
      out.write("\t\t\t\t//\txmldoc = parser.parseFromString(xmlstr, \"text/xml\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar m = [];\r\n");
      out.write("\t\t\t\tvar t = '';\r\n");
      out.write("\t\t\t\tvar lastNum = false;\r\n");
      out.write("\t\t\t\tfor(var i=0;i<xmlstr.length;i++){\r\n");
      out.write("\t\t\t\t\tvar tmp = xmlstr.charAt(i);\r\n");
      out.write("\t\t\t\t\tif(tmp!=','){\r\n");
      out.write("\t\t\t\t\t\tt += tmp;\r\n");
      out.write("\t\t\t\t\t\tlastNum = true;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tif(t != ''){\r\n");
      out.write("\t\t\t\t\t\t\tm.push(t);\r\n");
      out.write("\t\t\t\t\t\t\tt = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tlastNum = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(t != ''){\r\n");
      out.write("\t\t\t\t\tm.push(t);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tcallBack(m);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcatch (e) {\r\n");
      out.write("\t\t\t\t\talert(e.message+xmlstr);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar create = function (url, r) {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("   // Firefox, Opera 8.0+, Safari\r\n");
      out.write("\t\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tcatch (e) {\r\n");
      out.write("\r\n");
      out.write("   // Internet Explorer\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\txmlHttp = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch (e) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\txmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcatch (e) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar string = \"roleName=\"+name;\r\n");
      out.write("\t\txmlHttp.onreadystatechange = r;\r\n");
      out.write("\t\txmlHttp.open(\"post\", url, true);\r\n");
      out.write("\t\txmlHttp.setRequestHeader(\"content-length\",string.length);  \r\n");
      out.write("\t\txmlHttp.setRequestHeader(\"content-type\",\"application/x-www-form-urlencoded\");  \r\n");
      out.write("\t\txmlHttp.send(string);\r\n");
      out.write("\t};\r\n");
      out.write("\tcreate(url, r);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getSelect(){\r\n");
      out.write("\tvar selectedList1 = document.getElementById(\"unames\");\r\n");
      out.write("\tvar selectedList2 = document.getElementById(\"gifts\");\r\n");
      out.write("\tvar selectedList3=  document.getElementById(\"serverids\");\r\n");
      out.write("\tfor(var i=0;i<selectedList1.length;i++){\r\n");
      out.write("\t\tselectedList1.options[i].selected = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tfor(var i=0;i<selectedList2.length;i++){\r\n");
      out.write("\t\tselectedList2.options[i].selected = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tfor(var i=0;i<selectedList3.length;i++){\r\n");
      out.write("\t   selectedList3.options[i].selected = true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
